### PR TITLE
Dotenv

### PR DESCRIPTION
**Pull request by umar-muneer**

### CODE REVIEW

**Review by WaleedAshraf — CHANGES_REQUESTED** [review]
change Procfile to
`web: bin/www`

and remove CONFIG.json from .gitignore

**Comment by umar-muneer** [comment]
Okay I'll take a look

**Comment by umar-muneer** [comment]
Don't think we need to make these changes in the proc file. The proc file
loads envs and calls the shell script.. The www file does that too. It is
basically equivalent to the proc file but just for running locally

**Comment by umar-muneer** [comment]
But I will take a look anyway. Let's see

**Review by WaleedAshraf — COMMENTED** [review]
LGTM!

**Review by WaleedAshraf — APPROVED** [review]

**Pull request merged**
